title: Jae-woo's blog
email: wnwodn4293@naver.com
description: FE개발자를 꿈꾸며 공부내용을 올리는 블로그 입니다.
baseurl: ""
url: "https://joojaewoo.github.io"
github_username: joojaewoo
social:
  name: jae-woo
  email: wnwodn4293@naver.com
  links:
    - https://github.com/joojaewoo

google_site_verification: google-site-verification=MKnrYnihpuylpoPueT1803M7dgeR2SPGQRHHFRadG-s

avatar: https://user-images.githubusercontent.com/46195613/117643526-75eae700-b1c3-11eb-8904-9905dd44c312.jpg
paginate: 10

toc: true

disqus:
  comments: true # boolean type, the global switch for posts comments.
  shortname: "jaew-woo" # Fill with your Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname

markdown: kramdown

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts: # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: highlight
    # default_lang: console
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

collections:
  tabs:
    output: true
    sort_by: order

defaults:
  - scope:
      path: "" # An empty string here means all files in the project
      type: posts
    values:
      layout: post
      comments: true # Enable comments in posts.
      toc: true
      permalink: /posts/:title/
  - scope:
      path: ""
      type: tabs # see `site.collections`
    values:
      layout: page
      permalink: /:title/
      dynamic_title: true # Hide title in mobile screens.

sass:
  style: compressed

compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  blanklines: false
  ignore:
    envs: [development]

jekyll-archives:
  enabled: [categories, tags]
  layouts:
    category: category
    tag: tag
  permalinks:
    tag: /tags/:name/
    category: /categories/:name/

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - README.md
  - Rakefile
  - Gemfile
  - Gemfile.lock
  - changelog.md
  - "*.Rmd"
  - vendor
  - .travis.yml
  - node_modules
